{
 "title": "Flink",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "State",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "flink_taskmanager_job_task_operator_sync_time_avg"
    }
   ]
  },
  { "title": "JobManager", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Memory used",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "flink_jobmanager_Status_JVM_Memory_Heap_Used",
     "legendFormat": "heap memory [{{instance}}]"
    },
    {
     "expr": "flink_jobmanager_Status_JVM_Memory_NonHeap_Used",
     "legendFormat": "non-heap memory [{{instance}}]"
    }
   ]
  },
  {
   "title": "GC Overhead",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "rate(flink_jobmanager_Status_JVM_GarbageCollector_PS_MarkSweep_Time[5m])/1000 + rate(flink_jobmanager_Status_JVM_GarbageCollector_PS_Scavenge_Time[5m])/1000",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "TaskManager", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "Memory used",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "flink_taskmanager_Status_JVM_Memory_Heap_Used",
     "legendFormat": "heap memory [{{instance}}]"
    },
    {
     "expr": "flink_taskmanager_Status_JVM_Memory_NonHeap_Used",
     "legendFormat": "non-heap memory [{{instance}}]"
    }
   ]
  },
  {
   "title": "GC Overhead",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 37 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "rate(flink_taskmanager_Status_JVM_GarbageCollector_G1_Old_Generation_Time[5m])/1000 + rate(flink_taskmanager_Status_JVM_GarbageCollector_G1_Young_Generation_Time[5m])/1000",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "Queries", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 46 } },
  {
   "title": "Number Records In",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 47 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "flink_taskmanager_job_task_numRecordsIn",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Records out",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 47 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "flink_taskmanager_job_task_operator_numRecordsOut",
     "legendFormat": "{{quantile}}"
    }
   ]
  },
  {
   "title": "Bytes in",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 56 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "flink_taskmanager_job_task_numBytesInLocalPerSecond{job_name=\"Queries\"}",
     "legendFormat": "{{task_name}}"
    }
   ]
  },
  {
   "title": "Bytes out",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 56 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "flink_taskmanager_job_task_numBytesOutPerSecond{job_name=\"Queries\"}",
     "legendFormat": "{{task_name}}"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 65 },
   "repeat": "job",
   "format": "ms",
   "valueName": "current",
   "targets": [
    {
     "expr": "flink_jobmanager_job_uptime{job_name=\"$job\"}"
    }
   ]
  }
 ]
}