{
 "title": "Flink",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Latency Query 1 Monthly",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "flink_taskmanager_job_task_operator_Latency_Query1MONTHLY"
    }
   ]
  },
  {
   "title": "Latency Query 1 Weekly",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "flink_taskmanager_job_task_operator_Latency_Query1WEEKLY"
    }
   ]
  },
  {
   "title": "Latency Query 2 Monthly",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "flink_taskmanager_job_task_operator_Latency_Query2MONTHLY"
    }
   ]
  },
  {
   "title": "Latency Query 2 Weekly",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "flink_taskmanager_job_task_operator_Latency_Query2WEEKLY"
    }
   ]
  },
  {
   "title": "Latency Query 3 One hour",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "flink_taskmanager_job_task_operator_Latency_Query3ONE_HOUR"
    }
   ]
  },
  {
   "title": "Latency Query 3 Two hour",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "flink_taskmanager_job_task_operator_Latency_Query3TWO_HOUR"
    }
   ]
  },
  { "title": "JobManager", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "Memory used",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "flink_jobmanager_Status_JVM_Memory_Heap_Used",
     "legendFormat": "heap memory [{{instance}}]"
    },
    {
     "expr": "flink_jobmanager_Status_JVM_Memory_NonHeap_Used",
     "legendFormat": "non-heap memory [{{instance}}]"
    }
   ]
  },
  {
   "title": "GC Overhead",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 25 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "rate(flink_jobmanager_Status_JVM_GarbageCollector_PS_MarkSweep_Time[5m])/1000 + rate(flink_jobmanager_Status_JVM_GarbageCollector_PS_Scavenge_Time[5m])/1000",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "TaskManager", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "Memory used",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "flink_taskmanager_Status_JVM_Memory_Heap_Used",
     "legendFormat": "heap memory [{{instance}}]"
    },
    {
     "expr": "flink_taskmanager_Status_JVM_Memory_NonHeap_Used",
     "legendFormat": "non-heap memory [{{instance}}]"
    }
   ]
  },
  {
   "title": "GC Overhead",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 44 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "rate(flink_taskmanager_Status_JVM_GarbageCollector_G1_Old_Generation_Time[5m])/1000 + rate(flink_taskmanager_Status_JVM_GarbageCollector_G1_Young_Generation_Time[5m])/1000",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "Queries", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 52 } },
  {
   "title": "Records out",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 53 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(flink_taskmanager_job_task_operator_numRecordsOut) ",
     "legendFormat": "{{task}}"
    }
   ]
  },
  {
   "title": "Bytes out",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 53 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(flink_taskmanager_job_task_numBytesOutPerSecond{job_name=\"Queries\"})",
     "legendFormat": "{{task_name}}"
    }
   ]
  },
  {
   "title": "Number Records In",
   "type": "graph",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 63 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "flink_taskmanager_job_task_numRecordsIn",
     "legendFormat": "{{task_name}}"
    }
   ]
  },
  {
   "title": "Bytes in",
   "type": "graph",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 63 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "flink_taskmanager_job_task_numBytesInLocalPerSecond{job_name=\"Queries\"}",
     "legendFormat": "{{task_name}}"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 77 },
   "repeat": "job",
   "format": "ms",
   "valueName": "current",
   "targets": [
    {
     "expr": "flink_jobmanager_job_uptime{job_name=\"$job\"}"
    }
   ]
  }
 ]
}