---
global:
  scrape_interval: 1s
  evaluation_interval: 1s

rule_files:
- flink.rules.yml

scrape_configs:
- job_name: 'flink'
  static_configs:
  - targets: ['jobmanager:9251', 'taskmanager1:9251', 'taskmanager2:9251', 'taskmanager3:9251']
