---
global:
  scrape_interval: 1s
  evaluation_interval: 1s

rule_files:
- flink.rules.yml

scrape_configs:
- job_name: 'flink'
  static_configs:
  - targets: ['jobmanager:9251', 'cluster_taskmanager_1:9251', 'cluster_taskmanager_2:9251', 'cluster_taskmanager_3:9251']
