version: "2"

services:

  # Zookeeper
  zookeeper:
    image: docker.io/bitnami/zookeeper:latest
    ports:
      - "2181:2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
      
  # Broker 1 di Kafka
  broker1:
    image: docker.io/bitnami/kafka:latest
    ports:
      - "9093:9093"
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_LISTENERS=CLIENT://:9092,EXTERNAL://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=CLIENT://broker1:9092,EXTERNAL://localhost:9093
      - KAFKA_INTER_BROKER_LISTENER_NAME=CLIENT
    depends_on:
      - zookeeper
      
  # Broker 2 di Kafka
  broker2:
    image: docker.io/bitnami/kafka:latest
    ports:
      - "9094:9093"
    
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_LISTENERS=CLIENT://:9092,EXTERNAL://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=CLIENT://broker2:9092,EXTERNAL://localhost:9094
      - KAFKA_INTER_BROKER_LISTENER_NAME=CLIENT
        
    depends_on:
      - zookeeper
      
  # Master Flink
  jobmanager:
    build: ./Flink
    ports:
      - "8081:8081"
    command: jobmanager
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
        metrics.reporter.prom.class: org.apache.flink.metrics.prometheus.PrometheusReporter
        metrics.reporter.prom.port: 9251
        metrics.system-resource: true
        metrics.system-resource-probing-interval: 100
        metrics.latency.interval: 100
        metrics.latency.granularity: single
        state.backend.latency-track.keyed-state-enabled: true
        state.backend.rocksdb.metrics.actual-delayed-write-rate: true
        state.backend.rocksdb.metrics.background-errors: true
        state.backend.rocksdb.metrics.num-deletes-imm-mem-tables: true
        state.backend.rocksdb.metrics.num-entries-imm-mem-tables: true
        state.backend.rocksdb.metrics.num-snapshots: true
      - APP_GOAL=flinkjob

  # Worker Flink
  taskmanager:
    build: ./Flink
    command: taskmanager
    scale: 3
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
        taskmanager.numberOfTaskSlots: 3
        metrics.reporter.prom.class: org.apache.flink.metrics.prometheus.PrometheusReporter
        metrics.reporter.prom.port: 9251
        metrics.system-resource: true
        metrics.system-resource-probing-interval: 100
        metrics.latency.interval: 100
        metrics.latency.granularity: single
        state.backend.latency-track.keyed-state-enabled: true
        state.backend.rocksdb.metrics.actual-delayed-write-rate: true
        state.backend.rocksdb.metrics.background-errors: true
        state.backend.rocksdb.metrics.num-deletes-imm-mem-tables: true
        state.backend.rocksdb.metrics.num-entries-imm-mem-tables: true
        state.backend.rocksdb.metrics.num-snapshots: true
    depends_on:
      - jobmanager
    
  # Producer/Consumer Java
  app:
    build: ./AppSource
    depends_on:
      - zookeeper
      - broker1
      - broker2
      - jobmanager
      - taskmanager
    environment:
      - APP_GOAL=client
      
  # Prometheus
  prometheus:
    image: prom/prometheus:v2.27.1
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus/flink.rules.yml:/etc/prometheus/flink.rules.yml
    depends_on:
      - taskmanager

  # Grafana
  grafana:
    image: grafana/grafana:7.5.7
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=flink
    volumes:
      - ./grafana/provisioning/:/etc/grafana/provisioning/
    depends_on:
      - prometheus
      
      
      
      

