FROM flink:1.13.0-scala_2.11
USER root


ADD ./oshi-core-3.4.0.jar /opt/flink/lib/oshi-core-3.4.0.jar
ADD ./jna-4.2.2.jar /opt/flink/lib/jna-4.2.2.jar
ADD ./jna-platform-4.2.2.jar /opt/flink/lib/jna-platform-4.2.2.jar


